import React from "react";

import Head from 'next/head';
import MarkdownParser from '@/components/MarkdownParser/MarkdownParser';
import Navbar from '@/components/Navbar/Navbar';
import './Home.scss';
import Sidebar from '@/components/Sidebar/Sidebar';

import { useSelector } from 'react-redux';
import type { RootState } from "@/store/store";

import { useAuthState } from "react-firebase-hooks/auth";

export default function Home() {
  const file = useSelector((state: RootState) => state.app.file);
  const showSidebar = useSelector((state: RootState) => state.app.showSidebar);

  const autoSave = (content: string) => {
    console.log('updating save state...');
    // move this into axios request response
    const now = new Date();
    const time = now.toLocaleTimeString("en-GB", { hour12: true });
    console.log('last saved at: ' + time);
  }

  return (
    <>
      <Head>
        <title>wizzy wig</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <Navbar />
        <div className='container'>
          <Sidebar />
          <div 
            className={`md-container ${!showSidebar && 'sidebar-hidden'}`}
          >
            <MarkdownParser 
              updateSaveState={autoSave}
              content={file}
            />
          </div>
        </div>
      </div>
    </>
  )
}
